version: '3'
services:
#mssql docker
  veterinarskastanica-sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    expose:
        - 1433
    networks:
      - veterinarskastanicanet2022

  veterinarskastanica-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=veterinarskastanica-sql,1433;Database=VeterinarskaStanica;User=sa;Password=QWElkj132!;ConnectRetryCount=0; TrustServerCertificate=True 
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5192:5192
    networks:
      - veterinarskastanicanet2022
    links:
      - veterinarskastanica-sql
    depends_on:
      - veterinarskastanica-sql
      
networks:
  veterinarskastanicanet2022:
    driver: bridge      